apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "bbc.fullname" . }}
  labels:
    {{- include "bbc.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"

spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-frontend
      port:
        number: {{ .Values.frontend.port }}

  rules:
  - http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-api
            port:
              number: 80
