apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}

    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.name | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.port }}
          name: "http"

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
