apiVersion: v1
kind: Service

metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}

spec:
  ports:
    - port: {{ .Values.port }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
