apiVersion: v1
kind: Service

metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}

spec:
  ports:
    - port: 80
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
