name: CI

on:
  push:
    branches:
      - latest

jobs:
  apiQA:
    name: Quality assurance for REST API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check
        run: docker build -f api/Dockerfile --target=qa -t api api/

  frontendQA:
    name: Quality assurance for frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check
        run: docker build -f frontend/Dockerfile --target=qa -t frontend frontend/

  publish:
    name: Publish
    needs: [apiQA, frontendQA]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: skaffold build

      - name: Deploy
        run: |
          echo "TODO: deploy to some Kubernetes cluster"
