name: CI

on:
  push:
    branches:
      - latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Quality assurance for REST API
        run: docker build -f api/Dockerfile --target=qa -t api api/

      - name: Quality assurance for frontend
        run: docker build -f frontend/Dockerfile --target=qa -t frontend frontend/
